Update maven.yml

diff --git a/.github/workflows/maven.yml b/.github/workflows/maven.yml
--- a/.github/workflows/maven.yml
+++ b/.github/workflows/maven.yml
@@ -12,48 +12,39 @@ env:
 jobs:
   startrunner:
     runs-on: ubuntu-latest
-    outputs:
-      runner: ${{ steps.readid.outputs.runner }}
-      runnerflag: ${{ steps.readid.outputs.flag }}
     steps:
-      - uses: actions/checkout@v3
-      - id: readid
+      - name: test
+        continue-on-error: true          # make the step always success
+        id: test
         run: |
-           input='${{ github.workspace }}/InstanceID.txt'
-           while IFS= read -r line
-           do
-             echo "$line"
-             status=$(aws ec2 describe-instance-status --instance-id $line | jq -r '.InstanceStatuses[] | .InstanceState | .Name')
-             if [ "$status" != "running" ];then
-               aws ec2 start-instances --instance-ids $line
-               echo "::set-output name=runner::$line"
-               echo "::set-output name=flag::true"
-               break
-             fi
-             echo "::set-output name=flag::false"
-           done < "$input"
-           sleep 60
-#   Runner-status-check:
-#     needs: startrunner
-#     runs-on: ubuntu-latest
-#     if: ${{ needs.startrunner.outputs.flag }} == 'false'
-    
-    
-  build:
-     needs: startrunner
-     runs-on: self-hosted
-     steps:
-        - run: |
-           echo "Hello World"
-           sleep 180
-           
-  stop_runner:
-    needs: [build, startrunner]
-    runs-on: ubuntu-latest
-    steps:
-      - run: |
-          aws ec2 stop-instances --instance-ids ${{ needs.startrunner.outputs.runner }}
-        
+          exit 1                         # let's say 1st failed. for you, here could be mvn deploy command.
+      - name: retry
+        continue-on-error: true
+        id: retry1
+        if: steps.test.outcome=='failure'         # check the step outcome, retry 1st time
+        run: |
+          exit 1                                # if it fails again. if it's succeeds, the latter steps will be skipped, and status is successful.
+      - name: retry 2
+        continue-on-error: true
+        id: retry2
+        if: steps.retry1.outcome=='failure'   # check the step outcome, retry 2nd time
+        run: |
+          echo retry 2nd time
+          exit 1                                            # fail again
+      - name: retry 3
+        continue-on-error: true
+        id: retry3
+        if: steps.retry2.outcome=='failure'      # check the step outcome, retry 3rd time
+        run: |
+          echo retry 3rd time                 # it passed in retry 3
+      - name: set the status              # set the workflow status if command failed
+        if: always()
+        run: |
+          if ${{ steps.test.outcome=='success' || steps.retry1.outcome=='success' || steps.retry2.outcome=='success' || steps.retry3.outcome=='success' }}; then
+             echo fine
+          else
+             exit 1
+          fi
    
          
 
